In [1]:
import numpy as np

In [ ]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。

In [ ]:
#2.呈上題，將以上數列取出偶數。

In [ ]:
#3.呈1題，將數列取出3的倍數。

In [5]:
# 使用 arange方法
a = np.arange(0, 21, 1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [6]:
a[0::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
a[3::3]

array([ 3,  6,  9, 12, 15, 18])

In [16]:
# 使用 linspace方法
a = np.linspace(0, 20, 21, dtype='i4')
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [17]:
a[0::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [18]:
a[3::3]

array([ 3,  6,  9, 12, 15, 18])