作業目標

熟悉陣列維度轉換，並且會擷取需要資料

作業重點

使用reshap須注意order用法

where可以運用邏輯條件擷取資料 


題目:
1. 將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
2. 呈上題的array，找出被6除餘1的數的索引

In [44]:
import numpy as np

In [46]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))

In [47]:
#2.呈上題的array，找出被6除餘1的數的索引

In [48]:
b = np.reshape(array1,(5, 6), order="F")

In [49]:
b

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [53]:
np.nonzero(np.where(b % 6 == 1,1,0))
# 題目要求之索引為 [0, 5],[1, 0],[2, 1],[3, 2],[4, 3]

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))

如果不另設變數b, array1 reshape後資料在記憶體中仍以一維方式存放，順序不變

In [51]:
np.reshape(array1, (5, 6), order="F") #訪問方式改變, array1實際資料不變

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [52]:
np.nonzero(np.where(array1 % 6 == 1,1,0)) # 仍為一維列表的索引

(array([ 1,  7, 13, 19, 25], dtype=int64),)