In [2]:
import numpy as np

作業目標<br>
讀取存取陣列資料<br>
作業重點<br>
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [3]:
#1. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

In [4]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
array3 = np.array([[4,5,6], [1,2,3]])

In [37]:
#ANS.1
array1 = np.array(range(30))
array2 = np.array([2,3,5])

with open('homework1.npz', 'wb') as f:
    np.savez(f, a1=array1, a2=array2)

In [38]:
#ANS2.
hwfile = np.load('homework1.npz')
print(hwfile.files)
print(hwfile['a1'])
print(hwfile['a2'])

['a1', 'a2']
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [39]:
with open('homework1.npz', 'wb') as f:
    np.savez(f, hwfile['a1'], hwfile['a2'], array3)
hwfile = np.load('homework1.npz')
print(hwfile.files)
print(hwfile['arr_0'])
print(hwfile['arr_1'])
print(hwfile['arr_2'])    

['arr_0', 'arr_1', 'arr_2']
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[[4 5 6]
 [1 2 3]]
